export const ProjectArray = [
  {
    id: 1,
    img: require("../../images/Code4Justice.png"),
    title: "Habitat Healing",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae sequi maiores illo, qui vel nobis dicta et. Doloremque aut quas voluptatibus. Nobis, modi voluptates minima aut odit itaque. Consectetur, sapiente.",
    deployed: "https://code-for-justice.vercel.app/",
    github: "https://github.com/juniorLeon1/Code-for-Justice.git",
  },
  {
    id: 2,
    img: require("../../images/eCom1.png"),
    title: "The Toolbox 1",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae sequi maiores illo, qui vel nobis dicta et. Doloremque aut quas voluptatibus. Nobis, modi voluptates minima aut odit itaque. Consectetur, sapiente.",
    deployed: "https://e-commerce-xi-ochre.vercel.app/index.html",
    github: "https://github.com/juniorLeon1/eCommerce.git",
  },
  {
    id: 3,
    img: require("../../images/hopeHacks.png"),
    title: "SpeakEasy!",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae sequi maiores illo, qui vel nobis dicta et. Doloremque aut quas voluptatibus. Nobis, modi voluptates minima aut odit itaque. Consectetur, sapiente.",
    deployed: "https://github.com/juniorLeon1/hopeHacksTeam5.git",
    github: "https://github.com/juniorLeon1/hopeHacksTeam5.git",
  },
  {
    id: 4,
    img: require("../../images/WeatherApp.png"),
    title: "The Weather App",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae sequi maiores illo, qui vel nobis dicta et. Doloremque aut quas voluptatibus. Nobis, modi voluptates minima aut odit itaque. Consectetur, sapiente.",
    deployed: "https://github.com/juniorLeon1/weather-app-deploy-hbs.git",
    github: "https://github.com/juniorLeon1/weather-app-deploy-hbs.git",
  },
  {
    id: 5,
    img: require("../../images/eCom2.png"),
    title: "The Toolbox 2",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae sequi maiores illo, qui vel nobis dicta et. Doloremque aut quas voluptatibus. Nobis, modi voluptates minima aut odit itaque. Consectetur, sapiente.",
    deployed: "https://silver-alfajores-3b1022.netlify.app/",
    github: "https://github.com/juniorLeon1/eCommerce-V2.git",
  },
  {
    id: 6,
    img: require("../../images/CapStone.png"),
    title: "AvoTraveler",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae sequi maiores illo, qui vel nobis dicta et. Doloremque aut quas voluptatibus. Nobis, modi voluptates minima aut odit itaque. Consectetur, sapiente.",
    deployed: "https://rv-capstone.vercel.app/",
    github: "https://github.com/juniorLeon1/RV-Capstone.git",
  },
];
